#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8D v0.6 * Growing house and irrigation controlling and monitoring system |
# | Copyright (C) 2020-2024 Pozsár Zsolt <pozsarzs@gmail.com>                  |
# | get                                                                        |
# | get external library packages                                              |
# +----------------------------------------------------------------------------+

wget http://portio.inrim.it/portio-0.5.tar.gz
wget https://github.com/pymodbus-dev/pymodbus/archive/refs/tags/v3.6.8.tar.gz -O pymodbus-3.6.8.tar.gz

