#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8D v0.6 * Growing house and irrigation controlling and monitoring system |
# | Copyright (C) 2020-2024 Pozsár Zsolt <pozsarzs@gmail.com>                  |
# | prepare                                                                    |
# | Prepare OS                                                                 |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.2 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

line()
{
  for ((i=0; i<${#SWCR}; i++))
  do
    echo -n "-"
  done
  echo ""
}

# constants
ARCH=`uname -m`
SWN1="MM8D"
SWN2="mm8d"
SWCR=`cat documents/copyright`
SWV=`cat documents/VERSION`

# installer
echo -e "\n$SWN1 v$SWV prepare OS"
echo "$SWCR"
line
sleep 1
echo "Installing required components..."
sudo apt-get install apache2 \
                     build-essential \
                     git \
                     gnuplot \
                     libconfig-tiny-perl \
                     libfreetype6-dev \
                     libjpeg-dev \
                     libswitch-perl \
                     python3-daemon \
                     python3-dev \
                     python3-numpy \
                     python3-openssl \
                     python3-pip \
                     python3-requests \
                     python3-serial \
                     python3-setuptools \
		     python3-iniparse \
		     pip \
                     sudo \
                     wget

if [ "$ARCH" = "armhf" ]
then
  sudo apt-get install python3-rpi.gpio
else
  sudo pip install portio
fi

sudo pip install pymodbus

echo -e "\nSetting Apache2..."
sudo ln --force --symbolic /etc/apache2/mods-available/cgid.load /etc/apache2/mods-enabled/
sudo ln --force --symbolic /etc/apache2/mods-available/cgid.conf /etc/apache2/mods-enabled/
sudo ln --force --symbolic /etc/apache2/conf-available/serve-cgi-bin.conf /etc/apache2/conf-enabled/
sudo /etc/init.d/apache2 restart
echo -e "\nDone."
