#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8D v0.4 * Growing house and irrigation controlling and monitoring system |
# | Copyright (C) 2020-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | get                                                                        |
# | get library packages                                                       |
# +----------------------------------------------------------------------------+

wget http://portio.inrim.it/portio-0.5.tar.gz
