# +----------------------------------------------------------------------------+
# | MM8D v0.2 * Growing house controlling and remote monitoring device         |
# | Copyright (C) 2020-2021 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm8d_hu.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=MM8D
msg02=Telephely
msg03=Felhasználó
msg04=Név
msg05=Cím
msg06=Sátrak
msg07=Csatornák
msg08=Csatorna
msg09=Részletek
msg10=Elnevezések
msg11=Hőmérséklet &deg;C-ban
msg12=Relatív páratartalom %-ban
msg13=Relatív gáz koncentrátum %-ban
msg14=semleges
msg15=bekapcsolva
msg16=kikapcsolva
msg17=Működési mód (Hyphae/Mushroom)
msg18=Kézi működtetés
msg19=Kismegszakítók
msg20=Riasztó
msg21=Világítás kimenet
msg22=Szellőztetés kimenet
msg23=Fűtés kimenet
msg24=Dátum
msg25=Idő
msg26=Utolsó állapot
msg27=Frissít
msg28=Kamera
msg29=Napló
msg30=A teljes naplóért jelentkezzen be SSH-val és futtassa a <i>mm8d-viewlog</i>-ot!
msg31=Kezdő oldal
msg32=Hálózati feszültség érzékelő
msg33=Kismegszakító
msg34=Kimenetek felülbírálása
msg35=A felülbírálás módosításához jelentkezzen be az egységbe SSH-val és használja a <i>mm5d-override</i> parancsot!
msg36=A környezeti jellemzők beállításához jelentkezzen be az egységbe SSH-val és használja a <i>mm5d-editenvirconf</i> parancsot!
