# +----------------------------------------------------------------------------+
# | MM8D v0.1 * Growing house controlling and remote monitoring device         |
# | Copyright (C) 2020 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>            |
# | mm8d_hu.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=MM8D
msg02=Telephely
msg03=Felhasználó
msg04=Név
msg05=Cím
msg06=Sátrak
msg07=Csatornák
msg08=Csatorna
msg09=Részletek
msg10=Elnevezések
msg11=MM7D Hőmérséklet &degC-ban
msg12=MM7D Relatív páratartalom %-ban
msg13=MM7D Relatív gáz koncentrátum %-ban
msg14=MM7D Jó értékek
msg15=MM7D Kívül az optimális tartományon
msg16=MM7D Rossz értékek
msg17=MM6D Működési mód (átszövetés/termesztés)
msg18=MM6D Kézi működtetés
msg19=MM6D Nyitott kismegszakító
msg20=MM6D Riasztási esemény érzékelve
msg21=MM6D Világítás kimenet
msg22=MM6D Szellőztetés kimenet
msg23=MM6D Fűtés kimenet
msg24=Dátum
msg25=Idő
msg26=Utolsó állapot
msg27=Frissít
msg28=Kamera
msg29=Napló
msg30=Ha szeretné látni a teljes naplót, jelentkezzen be az egységbe SSH-val és használja a <i>mm8d-viewlog</i> parancsot!
msg31=Kezdő oldal
msg32=Nincs hálózati feszültség
msg33=Nyitott kismegszakító
msg34=Riasztási esemény érzékelve
msg35=A sziréna működik
