# +----------------------------------------------------------------------------+
# | MM8D v0.1 * Growing house controlling and remote monitoring device         |
# | Copyright (C) 2020 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>            |
# | mm8d_hu.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=MM8D
msg02=Telephely
msg03=Felhasználó
msg04=Név
msg05=Cím
msg06=Sátrak
msg07=Csatornák
msg08=Csatorna
msg09=részletek
msg10=Names
msg11=MM7D Temperature in &degC
msg12=MM7D Relative humidity in %
msg13=MM7D Relative gas concentrate in %
msg14=MM7D Good values
msg15=MM7D Out of optimal range
msg16=MM7D Bad values
msg17=MM6D Operation mode (hyphae/mushroom)
msg18=MM6D Manual operation
msg19=MM6D Opened overcurrent breaker
msg20=MM6D Alarm event detected
msg21=MM6D Output lamps 
msg22=MM6D Output vents
msg23=MM6D Output heaters
msg24=Date
msg25=Time
msg26=Latest status
msg27=Refresh
msg28=Camera
msg29=Log
msg30=If you want to see full log, please login to device via SSH, and use <i>mm8d-viewlog</i> command.
