#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8D v0.1 * Growing house controlling and remote monitoring device         |
# | Copyright (C) 2020 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>            |
# | mm8d-viewer                                                                |
# | View status of all controllers                                             |
# +----------------------------------------------------------------------------+

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: cannot open configuration file
#   2: specified value is not number
#   3: wrong channel number

read -p "Channel (1-16): " CHANNEL
if [[ ! "$CHANNEL" =~ ^[0-9]+$ ]]; then 
  echo "ERROR #2: Specified value is not number!"
  exit 2
fi
if [ $CHANNEL -ge "0" ]
then
  if [ $CHANNEL -le "16" ]
  then
    if [ $CHANNEL -lt "10" ]
    then
      CHANNEL="0"$CHANNEL
    fi
    mm8d-viewer.bin $CHANNEL
  else
    echo "ERROR #3: Wrong channel number!"
    echo "Valid values: 0..16"
    exit 3
  fi
else
  echo "ERROR #3: Wrong channel number!"
  echo "Valid values: 0..16"
  exit 3
fi
exit 0
