#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8D v0.1 * Growing house controlling and remote monitoring device         |
# | Copyright (C) 2020-2021 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm8d-editenvirconf                                                         |
# | Edit environment configuration file                                        |
# +----------------------------------------------------------------------------+

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: cannot open configuration file
#   2: specified value is not number
#   3: wrong channel number

read -p "Channel (1-8): " CHANNEL
if [[ ! "$CHANNEL" =~ ^[0-9]+$ ]]; then 
  echo "ERROR #2: Specified value is not number!"
  exit 2
fi
if [ $CHANNEL -ge "1" ]
then
  if [ $CHANNEL -le "8" ]
  then
    CFGFILE="/usr/local/etc/mm8d/envir-ch"
    CFGFILE=$CFGFILE$CHANNEL".ini"
    if [ ! -f $CFGFILE ]
    then
      echo "ERROR #1: Cannot open $CFGFILE configuration file!"
      exit 1
    fi
    sudo mm8d-editenvirconf.bin $CFGFILE
    if [ $? -eq 0 ]
    then
      mm8d-stopdaemon
      mm8d-startdaemon
    fi
  else
    echo "ERROR #3: Wrong channel number!"
    echo "Valid values: 1..8"
    exit 3
  fi
else
  echo "ERROR #3: Wrong channel number!"
  echo "Valid values: 1..8"
  exit 3
fi
exit 0
