#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8D v0.5 * Growing house and irrigation controlling and monitoring system |
# | Copyright (C) 2020-2023 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm8d-editenvirconf                                                         |
# | Edit environment configuration file                                        |
# +----------------------------------------------------------------------------+

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.2 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: cannot open configuration file
#   2: specified value is not number
#   3: wrong channel number

USRLOCALDIR="1"
if [ $USRLOCALDIR -eq "1" ]
then
  CFGDIR="/usr/local/etc/mm8d"
else
  CFGDIR="/etc/mm8d"
fi

if [ $# -eq 0 ]
then
  read -p "Channel (0-8): " CHANNEL
else
  CHANNEL=$1
fi

if [[ ! "$CHANNEL" =~ ^[0-9]+$ ]]; then 
  echo "ERROR #2: Specified value is not number!"
  exit 2
fi
if [ $CHANNEL -ge "0" ]
then
  if [ $CHANNEL -le "8" ]
  then
    if [ $CHANNEL -eq "0" ]
      then CFGFILE="irrigator.ini"
      else CFGFILE="envir-ch$CHANNEL.ini"
    fi
    if [ ! -f "$CFGDIR/$CFGFILE" ]
    then
      echo "ERROR #1: Cannot open $CFGDIR/$CFGFILE configuration file!"
      exit 1
    fi
    if [ $CHANNEL -eq "0" ]
      then sudo mm8d-editirrconf.bin "$CFGDIR/$CFGFILE"
      else sudo mm8d-editenvirconf.bin "$CFGDIR/$CFGFILE"
    fi
    if [ $? -eq 0 ]
    then
      mm8d-stopdaemon
      mm8d-startdaemon
    fi
  else
    echo "ERROR #3: Wrong channel number!"
    echo "Valid values: 0..8"
    exit 3
  fi
else
  echo "ERROR #3: Wrong channel number!"
  echo "Valid values: 0..8"
  exit 3
fi
exit 0
