#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8D v0.1 * Growing house controlling and remote monitoring device         |
# | Copyright (C) 2020 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>            |
# | mm8d-creatediagrams                                                        |
# | Create diagrams for webpage                                                |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: cannot open configuration file
#   2: specified value is not number
#   3: wrong channel number

checkparameter()
{
  if [[ ! $1 =~ ^[0-9]+$ ]]; then 
    echo "ERROR #2: Specified value is not number!"
    exit 2
  fi
  if [ $1 -ge "1" ]
  then
    if [ $1 -le "16" ]
    then
      if [ $1 -lt "10" ]
      then
        CHANNEL="0"$1
      else
        CHANNEL=$1
      fi
    else
      echo "ERROR #3: Wrong channel number!"
      echo "Valid values: 1..16"
      exit 3
    fi
  else
    echo "ERROR #3: Wrong channel number!"
    echo "Valid values: 1..16"
    exit 3
  fi
}

loadconfiguration()
{
  #CFGFILE="/etc/mm8d/mm8d.ini"
  CFGFILE="/usr/local/etc/mm8d/mm8d.ini"
  if [ ! -f $CFGFILE ]
  then
    echo "ERROR #1: Cannot open $CFGFILE configuration file!"
    exit 1
  fi
  DIR_HTM=`cat $CFGFILE | grep dir_htm= | sed 's/dir_htm=//'`
  DIR_LOG=`cat $CFGFILE | grep dir_log= | sed 's/dir_log=//'`
  DIR_TMP=`cat $CFGFILE | grep dir_tmp= | sed 's/dir_tmp=//'`
  WEB_LINES=`cat $CFGFILE | grep web_lines= | sed 's/web_lines=//'`
}

creatediagrams()
{
  TMPFILE=$DIR_HTM"diagrams/mm8d-creatediagrams.tmp"
  LOGFILE=$DIR_LOG"mm8d-ch"$CHANNEL".log"

  EMPTYPIC=$DIR_HTM"pics/temperature-empty.png"
  PNGFILE=$DIR_HTM"diagrams/temperature-ch$CHANNEL.png"
  head -n $WEB_LINES $LOGFILE > $TMPFILE 2> /dev/null
  gnuplot 2> /dev/null << EOF
set lmargin at screen 0.10
set rmargin at screen 0.90
set bmargin at screen 0.10
set tmargin at screen 0.90
set datafile separator ","
set title ""
set ylabel ""
set yrange [0:30]
set xlabel ""
unset xtics
set style fill solid 1.00 noborder
set boxwidth 2 relative
set terminal png
set output "$PNGFILE"
plot "$TMPFILE" using 3:xticlabels(stringcolumn(2)) with lines title "T [degree C]" linecolor rgb 'red'
EOF
  if [ $? -ne 0 ]
  then
    cp $EMPTYPIC $PNGFILE
  fi

  EMPTYPIC="$DIR_HTM/pics/humidity-empty.png"
  PNGFILE=$DIR_HTM"diagrams/humidity-ch$CHANNEL.png"
  gnuplot 2> /dev/null << EOF
set lmargin at screen 0.10
set rmargin at screen 0.90
set bmargin at screen 0.10
set tmargin at screen 0.90
set datafile separator ","
set title ""
set ylabel ""
set yrange [0:110]
set xlabel ""
unset xtics
set style fill solid 1.00 noborder
set boxwidth 2 relative
set terminal png
set output "$PNGFILE"
plot "$TMPFILE" using 4:xticlabels(stringcolumn(2)) with lines title "RH [%]" linecolor rgb 'blue'
EOF
  if [ $? -ne 0 ]
  then
    cp $EMPTYPIC $PNGFILE
  fi

  EMPTYPIC=$DIR_HTM"pics/gasconcentrate-empty.png"
  PNGFILE=$DIR_HTM"diagrams/gasconcentrate-ch$CHANNEL.png"
  gnuplot 2> /dev/null << EOF
set lmargin at screen 0.10
set rmargin at screen 0.90
set bmargin at screen 0.10
set tmargin at screen 0.90
set datafile separator ","
set title ""
set ylabel ""
set yrange [0:110]
set xlabel ""
unset xtics
set style fill solid 1.00 noborder
set boxwidth 2 relative
set terminal png
set output "$PNGFILE"
plot "$TMPFILE" using 4:xticlabels(stringcolumn(2)) with lines title "Gas concentrate [%]" linecolor rgb 'green'
EOF
  if [ $? -ne 0 ]
  then
    cp $EMPTYPIC $PNGFILE
  fi
  rm --force $TMPFILE
}

usage()
{
  echo -e "\nUsage: $0 channel\n"
  exit 0
}

if [ $# -eq 0 ]
then
  usage
fi
checkparameter $1
loadconfiguration
creatediagrams
exit 0
