#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8D v0.1 * Growing house controlling and remote monitoring device         |
# | Copyright (C) 2020-2021 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm8d-viewlog                                                               |
# | View log file                                                              |
# +----------------------------------------------------------------------------+

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: cannot open configuration file
#   2: specified value is not number
#   3: wrong channel number
#   5: cannot open log file

USRLOCALDIR="1"
if [ $USRLOCALDIR -eq "1" ]
then
  CFGFILE="/usr/local/etc/mm8d/mm8d.ini"
else
  CFGFILE="/etc/mm8d/mm8d.ini"
fi

loadconfiguration()
{
  if [ ! -f $CFGFILE ]
  then
    echo "ERROR #1: Cannot open $CFGFILE configuration file!"
    exit 1
  fi
  DIR_LOG=`cat $CFGFILE | grep dir_log= | sed 's/dir_log=//'`
}

viewlogfile()
{
  if [ $CHANNEL -eq "00" ]
  then
    echo "Log file of Channel #"$CHANNEL":"
    echo "+------------+-------+---------+"
    echo "|    Date    | Time  |  MM8D   |"
    echo "+------------+-------+---------+"
    OLDIFS=$IFS
    IFS=,
    while read C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 C11 C12
    do
      echo "| $C1 | $C2 | $C3 $C4 $C5 $C6 |"
    done < $LOGFILE
    echo "+------------+-------+---------+"
    IFS=$OLDIFS
  else
    echo "Log file of Channel #"$CHANNEL":"
    echo "+------------+-------+------+------+------+---------------+"
    echo "|    Date    | Time  | Temp |  RH  |  Gas |     MM6D      |"
    echo "+------------+-------+------+------+------+---------------+"
    OLDIFS=$IFS
    IFS=,
    while read C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 C11 C12
    do
      if [ ${#C3} -eq "1" ]; then C3=" $C3"; fi
      if [ ${#C4} -eq "1" ]; then C4="  $C4"; fi
      if [ ${#C4} -eq "2" ]; then C4=" $C4"; fi
      if [ ${#C5} -eq "1" ]; then C5="  $C5"; fi
      if [ ${#C5} -eq "2" ]; then C5=" $C5"; fi
      echo "| $C1 | $C2 | $C3°C | $C4% | $C5% | $C6 $C7 $C8 $C9 $C10 $C11 $C12 |"
    done < $LOGFILE
    echo "+------------+-------+------+------+------+---------------+"
    IFS=$OLDIFS
  fi
}

# main function
read -p "Channel (0-8): " CHANNEL
if [[ ! "$CHANNEL" =~ ^[0-9]+$ ]]; then 
  echo "ERROR #2: Specified value is not number!"
  exit 2
fi
loadconfiguration
if [ $CHANNEL -ge "0" ]
then
  if [ $CHANNEL -le "8" ]
  then
    LOGFILE=$DIR_LOG"/mm8d-ch"
    LOGFILE=$LOGFILE$CHANNEL".log"
    if [ ! -f $LOGFILE ]
    then
      echo "ERROR #5: Cannot open $LOGFILE log file!"
      exit 5
    fi
    viewlogfile
  else
    echo "ERROR #3: Wrong channel number!"
    echo "Valid values: 0..8"
    exit 3
  fi
else
  echo "ERROR #3: Wrong channel number!"
  echo "Valid values: 0..8"
  exit 3
fi
exit 0
