#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8D v0.4 * Growing house and irrigation controlling and monitoring system |
# | Copyright (C) 2020-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm8d-viewlog                                                               |
# | View log file                                                              |
# +----------------------------------------------------------------------------+

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: cannot open configuration file
#   2: specified value is not number
#   3: wrong channel number
#   5: cannot open log file

USRLOCALDIR="1"
if [ $USRLOCALDIR -eq "1" ]
then
  CFGFILE="/usr/local/etc/mm8d/mm8d.ini"
else
  CFGFILE="/etc/mm8d/mm8d.ini"
fi

loadconfiguration()
{
  if [ ! -f $CFGFILE ]
  then
    echo "ERROR #1: Cannot open $CFGFILE configuration file!"
    exit 1
  fi
  DIR_LOG=`cat $CFGFILE | grep dir_log= | sed 's/dir_log=//'`
}

viewlogfile()
{
  if [ $CHANNEL -eq "00" ]
  then
    echo ""
    echo "Log file of Channel #"$CHANNEL":"
    echo ""
    echo "1:  overcurrent breaker error            0: closed  1: opened"
    echo "2:  water pump pressure error (no water) 0: good    1: bad"
    echo "3:  water pump pressure error (clogging) 0: good    1: bad"
    echo "4:  external temperature"
    echo "5:  status of water pump and tube #1     0: off     1: on"
    echo "6:  status of water pump and tube #2     0: off     1: on"
    echo "7:  status of water pump and tube #3     0: off     1: on"
    echo ""
    echo "+------------+-------+------------------+"
    echo "|    Date    | Time  | 1 2 3  4   5 6 7 |"
    echo "+------------+-------+------------------+"
    OLDIFS=$IFS
    IFS=,
    while read C1 C2 C3 C4 C5 C6 C7 C8 C9 C10
    do
      if [ ${#C6} -eq "1" ]; then C6=" $C6"; fi
      echo "| $C1 | $C2 | $C3 $C4 $C5 $C6°C $C7 $C8 $C9 |"
    done < $LOGFILE
    echo "+------------+-------+------------------+"
    IFS=$OLDIFS
  else
    echo ""
    echo "Log file of Channel #"$CHANNEL":"
    echo ""
    echo " 1: temperature"
    echo " 2: relative humidity"
    echo " 3: relative unwanted gas concentrate"
    echo " 4: operation mode                        0: hyphae  1: mushroom"
    echo " 5: manual mode                           0: auto    1: manual"
    echo " 6: overcurrent breaker error             0: closed  1: opened"
    echo " 7: status of door (alarm)                0: closed  1: opened"
    echo " 8: status of lamp output                 0: off     1: on"
    echo " 9: status of ventilator output           0: off     1: on"
    echo "10: status of heater output               0: off     1: on"
    echo ""
    echo "+------------+-------+------------------------------+"
    echo "|    Date    | Time  |  1    2     3  4 5 6 7 8 9 10|"
    echo "+------------+-------+------------------------------+"
    OLDIFS=$IFS
    IFS=,
    while read C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 C11 C12
    do
      if [ ${#C3} -eq "1" ]; then C3=" $C3"; fi
      if [ ${#C4} -eq "1" ]; then C4="  $C4"; fi
      if [ ${#C4} -eq "2" ]; then C4=" $C4"; fi
      if [ ${#C5} -eq "1" ]; then C5="  $C5"; fi
      if [ ${#C5} -eq "2" ]; then C5=" $C5"; fi
      echo "| $C1 | $C2 | $C3°C $C4% $C5% $C6 $C7 $C8 $C9 $C10 $C11 $C12 |"
    done < $LOGFILE
    echo "+------------+-------+------------------------------+"
    IFS=$OLDIFS
  fi
}

# main function
if [ $# -eq 0 ]
then
  read -p "Channel (0-8): " CHANNEL
else
  CHANNEL=$1
fi

if [[ ! "$CHANNEL" =~ ^[0-9]+$ ]]; then 
  echo "ERROR #2: Specified value is not number!"
  exit 2
fi
loadconfiguration
if [ $CHANNEL -ge "0" ]
then
  if [ $CHANNEL -le "8" ]
  then
    LOGFILE=$DIR_LOG"/mm8d-ch"
    LOGFILE=$LOGFILE$CHANNEL".log"
    if [ ! -f $LOGFILE ]
    then
      echo "ERROR #5: Cannot open $LOGFILE log file!"
      exit 5
    fi
    viewlogfile
  else
    echo "ERROR #3: Wrong channel number!"
    echo "Valid values: 0..8"
    exit 3
  fi
else
  echo "ERROR #3: Wrong channel number!"
  echo "Valid values: 0..8"
  exit 3
fi
exit 0
