#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8D v0.1 * Growing house controlling and remote monitoring device         |
# | Copyright (C) 2020 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>            |
# | mm8d-editenvirconf                                                         |
# | Edit environment configuration file                                        |
# +----------------------------------------------------------------------------+

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: specified value is not number
#   2: wrong channel number
#   3: cannot open configuration file

read -p "Channel (1-16): " channel
if [[ ! "$channel" =~ ^[0-9]+$ ]]; then 
  echo "ERROR #1: Specified value is not number!"
  exit 1
fi
if [ $channel -ge "1" ]
then
  if [ $channel -le "16" ]
  then
    CFGFILE="/usr/local/etc/mm8d/envir-ch"
    if [ $channel -lt "10" ]
    then
      CFGFILE=$CFGFILE"0"$channel".ini"
    else
      CFGFILE=$CFGFILE$channel".ini"
    fi
    if [ ! -f $CFGFILE ]
    then
      echo "ERROR #3: Cannot open $CFGFILE configuration file!"
      exit 1
    fi
    sudo mm8d-editenvirconf.bin $CFGFILE
    if [ $? -eq 0 ]
    then
      mm8d-stopdaemon
      mm8d-startdaemon
    fi
  else
    echo "ERROR #2: Wrong channel number!"
    echo "Valid values: 1..16"
    exit 2
  fi
fi
exit 0
