#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8D v0.1 * Growing house controlling and remote monitoring device         |
# | Copyright (C) 2020-2021 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu        |
# | mm8d-override                                                              |
# | Override output status                                                     |
# +----------------------------------------------------------------------------+
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: cannot open configuration file
#   2: specified value is not number
#   3: wrong channel number
#   6: wrong output name
#   7: wrong output state
#   8: cannot write output file

USRLOCALDIR="1"
if [ $USRLOCALDIR -eq "1" ]
then
  CFGFILE="/usr/local/etc/mm8d/mm8d.ini"
else
  CFGFILE="/etc/mm8d/mm8d.ini"
fi

loadconfiguration()
{
  if [ ! -f $CFGFILE ]
    then
      echo "ERROR #1: Cannot open $CFGFILE configuration file!"
      exit 1
  fi
  DIR_VAR=`cat $CFGFILE | grep dir_var= | sed 's/dir_var=//'`
}

checkparameter()
{
  if [[ ! $1 =~ ^[0-9]+$ ]]; then 
    echo "ERROR #2: Specified value is not number!"
    exit 2
  fi
  if [ $1 -ge "1" ]
  then
    if [ $1 -le "8" ]
    then
      CHANNEL=$1
    else
      echo "ERROR #3: Wrong channel number!"
      echo "Valid values: 1..8"
      exit 3
    fi
  else
    echo "ERROR #3: Wrong channel number!"
    echo "Valid values: 1..8"
    exit 3
  fi
}

writetofile()
{
  case $2 in
    "lamp") OF="out1";;
    "ventilator") OF="out2";;
    "heater") OF="out3";;
    *)\
      echo "ERROR #6: Wrong output name!"; \
      echo "Valid values: heater, lamp, ventilator"; \
      exit 6;;
  esac
  if [ $3 = "neutral" ] || [ $3 = "on" ] || [ $3 = "off" ]
  then
    sudo mkdir --parents $DIR_VAR$CHANNEL 2>/dev/null
    sudo echo -n $3 2>/dev/null 1> $DIR_VAR$CHANNEL"/"$OF
    if [ $? = 0 ]
    then
      echo "Output '"$2"' of channel #"$CHANNEL" is set to $3."
      exit 0
    else
      echo "ERROR #8 Cannot write "$DIR_VAR$CHANNEL"/"$OF" output file!"
      exit 8
    fi
  fi
  echo "ERROR #7: Wrong output state!"; \
  echo "Valid values: neutral, on, off"
  exit 7
}

getstatus()
{
  if [ -f "$DIR_VAR$CHANNEL/out1" ]
  then
    LAMP=`cat "$DIR_VAR$CHANNEL/out1"`
  else
    LAMP="neutral"
  fi
  if [ -f "$DIR_VAR$CHANNEL/out2" ]
  then
    VENT=`cat "$DIR_VAR$CHANNEL/out2"`
  else
    VENT="neutral"
  fi
  if [ -f "$DIR_VAR$CHANNEL/out3" ]
  then
    HEAT=`cat "$DIR_VAR$CHANNEL/out3"`
  else
    HEAT="neutral"
  fi
  echo "Output status of Channel #"$CHANNEL":"
  echo -e "- lamp:\t\t$LAMP"
  echo -e "- ventilator:\t$VENT"
  echo -e "- heater:\t$HEAT"
}

runfullscreenprogram()
{
  read -p "Channel (1-8): " CH
  checkparameter $CH
  sudo mm8d-override.bin $DIR_VAR$CHANNEL
}

usage()
{
  echo -e "\nUsage:"
  echo    "       $0 -f|--full-screen"
  echo    "       $0 channel"
  echo -e "       $0 channel heater|lamp|ventilator neutral|on|off\n"
  exit 0
}

if [ $# -eq 0 ]
then
  usage
fi
loadconfiguration
if [ $# -eq 1 ];
then
  case $1 in
    "-f") runfullscreenprogram; exit 0;;
    "--full-screen") runfullscreenprogram; exit 0;;
    *) checkparameter $1; getstatus; exit 0;;
  esac
fi
if [ $# -eq 3 ]
then
  checkparameter $1
  writetofile $1 $2 $3
  exit 0
fi
usage
exit 0
