#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8D v0.4 * Growing house and irrigation controlling and monitoring system |
# | Copyright (C) 2020-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm8d-editmainconf                                                          |
# | Edit main configuration file                                               |
# +----------------------------------------------------------------------------+

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: cannot open configuration file

USRLOCALDIR="1"
if [ $USRLOCALDIR -eq "1" ]
then
  CFGFILE="/usr/local/etc/mm8d/mm8d.ini"
else
  CFGFILE="/etc/mm8d/mm8d.ini"
fi

if [ ! -f $CFGFILE ]
then
  echo "ERROR #1: Cannot open $CFGFILE configuration file!"
exit 1
fi

sudo mm8d-editmainconf.bin $CFGFILE
if [ $? -eq 0 ]
then
  mm8d-stopdaemon
  mm8d-updatestartpage
  mm8d-startdaemon
fi
exit 0
