#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8D v0.1 * Growing house controlling and remote monitoring device         |
# | Copyright (C) 2020 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>            |
# | mm8d-maintainlog                                                           |
# | Maintain log file                                                          |
# +----------------------------------------------------------------------------+

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: cannot open configuration file
#   2: cannot create backup file

loadconfiguration()
{
  #CFGFILE="/etc/mm8d/mm8d.ini"
  CFGFILE="/usr/local/etc/mm8d/mm8d.ini"
  if [ ! -f $CFGFILE ]
    then
      echo "ERROR #1: Cannot open $CFGFILE configuration file!"
      exit 1
  fi
  LNG=`cat $CFGFILE | grep lng= | sed 's/lng=//'`
  DAY_LOG=`cat $CFGFILE | grep day_log= | sed 's/day_log=//'`
  DIR_LOG=`cat $CFGFILE | grep dir_log= | sed 's/dir_log=//'`
  DIR_LCK=`cat $CFGFILE | grep dir_lck= | sed 's/dir_lck=//'`
  DAY_L=$(($DAY_LOG+1))
}

maintainlogfile()
{
  DATAFILE=$DIR_LOG"mm8d-ch$1.log"
  BCKPFILE=$DIR_LOG"mm8d-ch$1.bak"

  rm --force $BCKPFILE.gz
  mv $DATAFILE $BCKPFILE
  touch $DATAFILE
  NOW=`date +%s`
  OLDIFS=$IFS
  IFS=,
  [ ! -f $BCKPFILE ] && { echo "ERROR #2: Cannot create $BCKPFILE backup file!"; exit 2; }
  while read C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 C11 C12 C13 C14 C15 C16
  do
    XDATE=`date -d $C1 +%s`
    MAXXDATE=$(($XDATE+$((86400*$DAY_L))))
    if ! [ $NOW -gt $MAXXDATE ]
    then
      echo "$C1,$C2,$C3,$C4,$C5,$C6,$C7,$C8,$C9,$C10,$C11,$C12,$C13,$C14,$C15,$C16" >> $DATAFILE
    fi
  done < $BCKPFILE
  IFS=$OLDIFS
  gzip -9 $BCKPFILE
}

# main function
loadconfiguration
for i in {1..9}
do
  maintainlogfile "0$i"
done
for i in {10..16}
do
  maintainlogfile "$i"
done
exit 0
