#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8D v0.5 * Growing house and irrigation controlling and monitoring system |
# | Copyright (C) 2020-2023 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm8d-updatestartpage                                                       |
# | Update startpage                                                           |
# +----------------------------------------------------------------------------+

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.2 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: cannot open configuration file

# constants
USRLOCALDIR="1"
if [ $USRLOCALDIR -eq "1" ]
then
  CFGFILE="/usr/local/etc/mm8d/mm8d.ini"
else
  CFGFILE="/etc/mm8d/mm8d.ini"
fi

loadconfiguration()
{
  if [ ! -f $CFGFILE ]
  then
    echo "ERROR #1: Cannot open $CFGFILE configuration file!"
    exit 1
  fi
  LNG=`cat $CFGFILE | grep lng= | sed 's/lng=//'`
  DIR_HTM=`cat $CFGFILE | grep dir_htm= | sed 's/dir_htm=//'`
  DIR_MSG=`cat $CFGFILE | grep dir_msg= | sed 's/dir_msg=//'`
  DIR_SHR=`cat $CFGFILE | grep dir_shr= | sed 's/dir_shr=//'`
  DIR_TMP=`cat $CFGFILE | grep dir_tmp= | sed 's/dir_tmp=//'`
  ENA_CH1=`cat $CFGFILE | grep ena_ch1= | sed 's/ena_ch1=//'`
  ENA_CH2=`cat $CFGFILE | grep ena_ch2= | sed 's/ena_ch2=//'`
  ENA_CH3=`cat $CFGFILE | grep ena_ch3= | sed 's/ena_ch3=//'`
  ENA_CH4=`cat $CFGFILE | grep ena_ch4= | sed 's/ena_ch4=//'`
  ENA_CH5=`cat $CFGFILE | grep ena_ch5= | sed 's/ena_ch5=//'`
  ENA_CH6=`cat $CFGFILE | grep ena_ch6= | sed 's/ena_ch6=//'`
  ENA_CH7=`cat $CFGFILE | grep ena_ch7= | sed 's/ena_ch7=//'`
  ENA_CH8=`cat $CFGFILE | grep ena_ch8= | sed 's/ena_ch8=//'`
  ENA_MM10D=`cat $CFGFILE | grep ena_mm10d= | sed 's/ena_mm10d=//'`
  ENA_SECCAMS=`cat $CFGFILE | grep ena_seccams= | sed 's/ena_seccams=//'`
  NAM_CH0=`cat $CFGFILE | grep nam_ch0= | sed 's/nam_ch0=//'`
  NAM_CH1=`cat $CFGFILE | grep nam_ch1= | sed 's/nam_ch1=//'`
  NAM_CH2=`cat $CFGFILE | grep nam_ch2= | sed 's/nam_ch2=//'`
  NAM_CH3=`cat $CFGFILE | grep nam_ch3= | sed 's/nam_ch3=//'`
  NAM_CH4=`cat $CFGFILE | grep nam_ch4= | sed 's/nam_ch4=//'`
  NAM_CH5=`cat $CFGFILE | grep nam_ch5= | sed 's/nam_ch5=//'`
  NAM_CH6=`cat $CFGFILE | grep nam_ch6= | sed 's/nam_ch6=//'`
  NAM_CH7=`cat $CFGFILE | grep nam_ch7= | sed 's/nam_ch7=//'`
  NAM_CH8=`cat $CFGFILE | grep nam_ch8= | sed 's/nam_ch8=//'`
  USR_NAM=`cat $CFGFILE | grep usr_nam= | sed 's/usr_nam=//'`
}

loadmessages()
{
  MSG01="MM8D"
  MSG03="User"
  MSG07="Pages"
  MSG08="Channel"
  MSG09="Details"
  MSG37="Environment"
  MSG70="Security cameras"
  MSG71="Electricity supply"
  MSG78="Water supply"

  MSGFILE="$DIR_MSG/$LNG/mm8d.msg"
  if [ -f "$MSGFILE" ]
  then
    MSG01=`cat $MSGFILE | grep msg01 | sed 's/msg01=//'`
    MSG03=`cat $MSGFILE | grep msg03 | sed 's/msg03=//'`
    MSG07=`cat $MSGFILE | grep msg07 | sed 's/msg07=//'`
    MSG08=`cat $MSGFILE | grep msg08 | sed 's/msg08=//'`
    MSG09=`cat $MSGFILE | grep msg09 | sed 's/msg09=//'`
    MSG37=`cat $MSGFILE | grep msg37 | sed 's/msg37=//'`
    MSG70=`cat $MSGFILE | grep msg70 | sed 's/msg70=//'`
    MSG71=`cat $MSGFILE | grep msg71 | sed 's/msg71=//'`
    MSG78=`cat $MSGFILE | grep msg78 | sed 's/msg78=//'`
  fi
}

makehomepage()
{
  # write footer
  if [ -f "$DIR_SHR/header_$LNG.html" ]
  then
    cat $DIR_SHR/header_$LNG.html > $DIR_TMP/index.html
  else
    cat $DIR_SHR/header_en.html > $DIR_TMP/index.html
  fi
  # write body
  cat >> "$DIR_TMP/index.html" << EOF
    <table border=0 cellspacing=0 cellpadding=6 width="100%">
      <tbody>
        <tr>
          <td colspan="2" class="header" align="center"><b class="title0">$MSG01</b></td>
        </tr>
      </tbody>
    </table>
    <br>
    <br>
    <table border="0" cellpadding="3" cellspacing="0" width="100%">
      <tbody>
        <tr>
          <td colspan="2"><b>$MSG03</b></td>
          <td align="right">$USR_NAM</td>
        </tr>
        <tr><td colspan="3">&nbsp;</td></tr>
        <tr>
          <td colspan="2"><b>$MSG70</b></td>
          <td align="right">
EOF
  if [ $ENA_SECCAMS == 1 ]
    then
      echo "            <a href=\"cgi-bin/getcameras.cgi\"><button type="button">$MSG09</button></a>">> $DIR_TMP/index.html
    else
      echo "            <a href=\"cgi-bin/getcameras.cgi\"><button type="button" disabled>$MSG09</button></a>">> $DIR_TMP/index.html
    fi
  cat >> "$DIR_TMP/index.html" << EOF
          </td>
        </tr>
        <tr>
          <td colspan="2"><b>$MSG71</b></td>
          <td align="right">
EOF
  if [ $ENA_MM10D == 1 ]
    then
      echo "            <a href=\"cgi-bin/getsupply.cgi?type=e\"><button type=\"button\">$MSG09</button></a>">> $DIR_TMP/index.html
    else
      echo "            <a href=\"cgi-bin/getsupply.cgi?type=e\"><button type=\"button\" disabled>$MSG09</button></a>">> $DIR_TMP/index.html
    fi
  cat >> "$DIR_TMP/index.html" << EOF
          </td>
        </tr>
        <tr>
          <td colspan="2"><b>$MSG78</b></td>
          <td align="right">
EOF
  if [ $ENA_MM10D == 1 ]
    then
      echo "            <a href=\"cgi-bin/getsupply.cgi?type=w\"><button type=\"button\">$MSG09</button></a>">> $DIR_TMP/index.html
    else
      echo "            <a href=\"cgi-bin/getsupply.cgi?type=w\"><button type=\"button\" disabled>$MSG09</button></a>">> $DIR_TMP/index.html
    fi
  cat >> "$DIR_TMP/index.html" << EOF
          </td>
        </tr>
        <tr><td colspan="3">&nbsp;</td></tr>
        <tr>
          <td><b>$MSG08 #0</b></td><td>$NAM_CH0</td>
          <td align="right">
            <a href="cgi-bin/getenvirconf.cgi?channel=0"><button type="button">$MSG37</button></a>&nbsp;
            <a href="cgi-bin/getchannel.cgi?channel=0"><button type="button">$MSG09</button></a>
          </td>
        </tr>
EOF
  for i in {1..8}
  do
    ii=$i
    NAME=NAM_CH$ii
    ENAB=ENA_CH$ii
    echo "        <tr>"  >> $DIR_TMP/index.html
    echo "          <td><b>$MSG08 #$ii</b></td><td>${!NAME}</td>"  >> $DIR_TMP/index.html
    echo -n "          <td align=\"right\">" >> $DIR_TMP/index.html
    if [ ${!ENAB} = 1 ]
    then
      echo "<a href=\"cgi-bin/getenvirconf.cgi?channel=$i\"><button type=\"button\">$MSG37</button></a>&nbsp;" >> $DIR_TMP/index.html
      echo "            <a href=\"cgi-bin/getchannel.cgi?channel=$i\"><button type=\"button\">$MSG09</button></a></td>" >> $DIR_TMP/index.html
    else
      echo "<a href=\"cgi-bin/getenvirconf.cgi?channel=$i\"><button type=\"button\" disabled>$MSG37</button></a>&nbsp;" >> $DIR_TMP/index.html
      echo "            <a href=\"cgi-bin/getchannel.cgi?channel=$i\"><button type=\"button\" disabled>$MSG09</button></a></td>" >> $DIR_TMP/index.html
    fi
    echo "        </tr>" >> $DIR_TMP/index.html
  done

  cat >> $DIR_TMP/index.html << EOF
      </tbody>
    </table>
    <br>
EOF
  # write footer
  if [ -f "$DIR_SHR/footer_$LNG.html" ]
  then
    cat $DIR_SHR/footer_$LNG.html >> $DIR_TMP/index.html
  else
    cat $DIR_SHR/footer_en.html >> $DIR_TMP/index.html
  fi
  sudo mv $DIR_TMP/index.html $DIR_HTM/index.html
  rm --force $DIR_TMP/index.html
}

# Main function
loadconfiguration
loadmessages
makehomepage
exit 0
