#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8D v0.5 * Growing house and irrigation controlling and monitoring system |
# | Copyright (C) 2020-2023 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm8d-maintainlog                                                           |
# | Maintain log file                                                          |
# +----------------------------------------------------------------------------+

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.2 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: cannot open configuration file
#   4: cannot create backup file

# constants
USRLOCALDIR="1"
if [ $USRLOCALDIR -eq "1" ]
then
  CFGFILE="/usr/local/etc/mm8d/mm8d.ini"
else
  CFGFILE="/etc/mm8d/mm8d.ini"
fi

loadconfiguration()
{
  if [ ! -f $CFGFILE ]
    then
      echo "ERROR #1: Cannot open $CFGFILE configuration file!"
      exit 1
  fi
  LNG=`cat $CFGFILE | grep lng= | sed 's/lng=//'`
  DAY_LOG=`cat $CFGFILE | grep day_log= | sed 's/day_log=//'`
  DIR_LOG=`cat $CFGFILE | grep dir_log= | sed 's/dir_log=//'`
  DIR_LCK=`cat $CFGFILE | grep dir_lck= | sed 's/dir_lck=//'`
  DAY_L=$(($DAY_LOG+1))
}

maintainlogfile()
{
  DATAFILE=$DIR_LOG"/$1.log"
  BCKPFILE=$DIR_LOG"/$1.bak"
  if [ -f $DATAFILE ]
  then
    rm --force $BCKPFILE.gz
    mv $DATAFILE $BCKPFILE
    touch $DATAFILE
    NOW=`date +%s`
    OLDIFS=$IFS
    IFS=,
    [ ! -f $BCKPFILE ] && { echo "ERROR #4: Cannot create $BCKPFILE backup file!"; exit 4; }
    if [ $1 = 0 ]
    then 
      while read C1 C2 C3 C4 C5 C6 C7 C8 C9
      do
        XDATE=`date -d $C1 +%s`
        MAXXDATE=$(($XDATE+$((86400*$DAY_L))))
        if ! [ $NOW -gt $MAXXDATE ]
        then
          echo "$C1,$C2,$C3,$C4,$C5,$C6,$C7,$C8,$C9" >> $DATAFILE
        fi
      done < $BCKPFILE
    else
      while read C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 C11 C12
      do
        XDATE=`date -d $C1 +%s`
        MAXXDATE=$(($XDATE+$((86400*$DAY_L))))
        if ! [ $NOW -gt $MAXXDATE ]
        then
          echo "$C1,$C2,$C3,$C4,$C5,$C6,$C7,$C8,$C9,$C10,$C11,$C12" >> $DATAFILE
        fi
      done < $BCKPFILE
    fi
    IFS=$OLDIFS
    gzip -9 $BCKPFILE
  fi
}

# main function
loadconfiguration
for i in {0..8}
do
  maintainlogfile "mm8d-ch$i"
done
maintainlog "mm8d-supply"
exit 0
